Acct mgt
vaultec81/3Speak-app pull request #7
Opened 2021-04-03 09:30 UTC by olatundeee

Added functions that helps to handle the following operations using a Hive account

- Voting and downvoting
- Commenting
- Following and unfollowing

2021-04-07 01:25 UTC, vaultec81 requested changes

2021-04-07 01:25 UTC, vaultec81 commented on src/renderer/components/video/PostComment.js
> +        const wif = ''; // posting key
Could you pull this information dynamically from the account system backend and only the author/permlink respectively?

2021-04-07 01:25 UTC, vaultec81 commented on src/renderer/components/widgets/Follow.js
> +        const username = '' // follower
Same here as above. Pull the information dynamically from account database/author to follow

2021-04-07 01:25 UTC, vaultec81 commented on src/renderer/components/widgets/Follow.js
> +        const what = '' // empty string, default value for an unfollow operation
What does "what" variable mean here? I am not super familiar with hive operations

2021-04-07 01:25 UTC, vaultec81 commented on src/renderer/utils.js
> +                    alert('Error encountered')
Don't alert user this way. Console.log is fine for the time being.

2021-04-07 01:25 UTC, vaultec81 commented on src/renderer/views/Accounts.js
> +        let accounts = ['username1', 'test2', 'etc3', 'anoitheeeeeeeeeeeeeer'];
Get accounts using the backend API then display appropriate information here.

2021-04-07 01:25 UTC, vaultec81 commented on src/renderer/views/Accounts.js
> +        //TODO: account switch
Save profile ID in `localStorage`.

2021-04-07 01:25 UTC, vaultec81 commented on src/renderer/views/Accounts.js
> +                                <b className='pr-2'>@{acc}</b> <img className='float-right mr-2' src={hive} width={15} height={15}/>
Is this case `acc` variable will most likely be an object with sub information about the specific accounts attached to the profile.

2021-04-13 19:05 UTC, olatundeee commented on src/renderer/components/widgets/Follow.js
> +        const what = '' // empty string, default value for an unfollow operation
The what variable specifies whether the ensuing operation is a `follow` or `unfollow` operation. For `unfollow` the value has to be empty. For `follow`, it takes the value `blog`

2021-04-18 21:09 UTC, vaultec81 requested changes
Take a look at the comments made

TODO:
- [ ] Resolve all/majority of my comments
- [ ] Fix CI build

2021-04-18 21:09 UTC, vaultec81 commented on src/renderer/components/video/PostComment.js
> +            const theWif = profile.keyring[0].private.key // posting key
Could you search the array instead of hardcoding an index of the array? `Arraysearch` (already installed and used in this project already) is one library that makes searching very easy

2021-04-18 21:09 UTC, vaultec81 commented on src/renderer/components/video/PostComment.js
> +            console.log('log in first')
Could you alert the user/redirect to login instead of console.log. The user would never see that they aren't logged in.

2021-04-18 21:09 UTC, vaultec81 commented on src/renderer/components/video/Vote.js
> +                const wif = profile.keyring[0].private.key; // posting key
Array search here is as well

2021-04-18 21:09 UTC, vaultec81 commented on src/renderer/utils.js
> +                                    }
Could you label `key` -> `posting_key` as we might want to add `active` key later on.

2021-04-18 21:09 UTC, vaultec81 commented on src/renderer/utils.js
> +                            }
Throw an error instead of returning an object

2021-04-18 21:09 UTC, vaultec81 commented on src/renderer/utils.js
> +                        const check_profile = (await PromiseIPC.send("accounts.has", profileID));
Please check if the account exists before doing any kind of key checking operations as show above

2021-04-18 21:09 UTC, vaultec81 commented on src/renderer/utils.js
> +                        console.log("Wrong password");
Throw an error here, and display visually to the user. Make sure you also include more verbose information about what is wrong, "invalid posting key" would be better.

2021-04-18 21:09 UTC, vaultec81 commented on src/renderer/views/Accounts.js
> +       localStorage.removeItem('SNProfileID');
Why is removeItem here? setItem does the job of replacing any previous data.. No need to run this.

2021-04-18 21:09 UTC, vaultec81 commented on src/renderer/views/Accounts.js
> +        }
Make use of `arraysearch` library

2021-04-18 21:09 UTC, vaultec81 commented on src/renderer/views/Accounts.js
> +        window.location.reload();
What is the reason behind window.location.reload()? This is unncessary.

2021-04-22 20:32 UTC, vaultec81 requested changes

2021-04-22 20:32 UTC, vaultec81 commented on src/renderer/components/video/Vote.js
> +        await arr.find(function(obj) {
The `arr.find` is not an async function. Purely a normal function. No need to have the exterior wrapper function as async

2021-04-22 20:32 UTC, vaultec81 commented on src/renderer/components/video/Vote.js
> +            wif = obj.privateKeys.posting_key
This logic will result in the posting key being undefined. Please use arraysearch library.

2021-04-22 20:32 UTC, vaultec81 commented on src/renderer/components/video/Vote.js
> +                alert('log in first')
Could you make use of the [react notifications library](https://www.npmjs.com/package/react-notifications) already in use around the project? It's just as simple but with better UI

2021-04-23 19:52 UTC, olatundeee commented on src/renderer/utils.js
> +                        const check_profile = (await PromiseIPC.send("accounts.has", profileID));
That line of code is to check for the account existence, not the key.

2021-04-25 02:59 UTC, vaultec81 reviewed
I am picking this up from now on. Will merge into the `feat/acct-mgt` branch where I can work on this separately.

2021-04-25 02:59 UTC, merged